### ISSUE TITLE
aruco_3X4_DICT_4X4 real size is not correct

### ISSUE THREAD

**Issue by portgasray** [intel/ros2_grasp_library#63]
@RoboticsYY  aruco maker [here](https://github.com/intel/ros2_grasp_library/blob/master/grasp_utils/handeye_target_detection/data/pattern/aruco_3X4_DICT_4X4_50.png) is out of place 
![aruco_size](https://user-images.githubusercontent.com/17681580/69493785-01988700-0eee-11ea-8eb8-70eaae8c52b2.png)

![real](https://user-images.githubusercontent.com/17681580/69493880-55f03680-0eef-11ea-8524-c23f136b8534.jpg)

**Comment by RoboticsYY** [comment]
@portgasray The size input to the target detection is the one you measured from your printed copy.  It could differ in different way of printing.
